---
language: python
python: "2.7"

# Set --extra-vars
env:
  - ROLENAME="ansible-role-template"

# Building Specific Git Branches
branches:
  only:
  - master
  - develop
  #- release
  #- feature
  #- hotfix

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --extra-vars "rolename=${ROLENAME}" --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/